export const DEFAULT_FINGERPRINT_SEED = 123412414

const DEFAULT_PLATFORM = 'web'

const DEFAULT_COOKIE_NAME = 'sp'

const DEFAULT_PAGE_UNLOAD_TIMER = 500

const DEFAULT_FORCE_SECURE_TRACKER = false

const DEFAULT_FORCE_UNSECURE_TRACKER = false

const DEFAULT_SESSION_COOKIE_TIMEOUT = 1300

const DEFAULT_USE_LOCAL_STORAGE = true

export const DEFAULT_OPTIONS = {
    platform: DEFAULT_PLATFORM,
    cookieName: DEFAULT_COOKIE_NAME,
    userFingerPrintSeed: DEFAULT_FINGERPRINT_SEED,
    pageUnloadTimer: DEFAULT_PAGE_UNLOAD_TIMER,
    forceSecureTracker: DEFAULT_FORCE_SECURE_TRACKER,
    forceUnsecureTracker: DEFAULT_FORCE_UNSECURE_TRACKER,
    sessionCookieTimeout: DEFAULT_SESSION_COOKIE_TIMEOUT,
    useLocalStorage: DEFAULT_USE_LOCAL_STORAGE
}
